// This file is automatically generated. Do not edit it directly.
// NOTE: This client should NOT be used. Use client.server.ts for server functions only.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // This should only be called on the server side via client.server.ts
  // Using this on the client will cause serialization errors
  throw new Error('Supabase client should not be used directly in browser. Use server functions instead.');
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

